env:
  browser: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - windows
  no-unused-vars:
    - error
    - varsIgnorePattern: should
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - always
  new-parens: error
  curly:
    - error
    - multi-line
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowPattern: ^[a-z]+(_[a-z]+)+$
  eqeqeq:
    - error
    - always
  # This works with continue!
  guard-for-in: error
  no-div-regex: error
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extra-bind: error
  no-extra-label: error
  no-global-assign: error
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-lone-blocks: error
  no-multi-spaces: error
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-proto: error
  no-return-await: error
  no-script-url: error
  no-self-assign:
    - error
    - props: true
  no-self-compare: error
  no-sequences: error
  no-unmodified-loop-condition: error
  no-useless-return: error
  no-void: error
  no-with: error
  require-await: error
  wrap-iife:
    - error
    - inside
  yoda:
    - error
    - never
    - exceptRange: true
  no-label-var: error
  no-shadow-restricted-names: error
  no-use-before-define: error
  array-bracket-spacing: error
  brace-style:
    - error
    - 1tbs
  camelcase:
    - error
    - properties: never
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  eol-last:
    - error
    - never
  func-call-spacing: error
  key-spacing: error
  max-len: error
  no-array-constructor: error
  no-lonely-if: error
  no-negated-condition: error
  no-new-object: error
  no-tabs: error
  no-trailing-spaces:
    - error
    - skipBlankLines: true
  no-whitespace-before-property: error
  operator-linebreak:
    - error
    - before
  semi-spacing: error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  spaced-comment:
    - error
    - always
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  prefer-arrow-callback: error
  prefer-numeric-literals: error
  prefer-spread: error
  rest-spread-spacing: error
  template-curly-spacing: error
  no-var: error