#%RAML 1.0

# TODO: XML support? Should we offer YAML support?
# TODO: security schemes
# TODO: split into multiple files, eventually

title: Library App
description: >
  An app for a school (and possibly general) library. Currently in the early
  development/design stages, will change a lot.
version: v0
baseUri: /{version}
mediaType:
  - application/json
  - application/yaml
