#%RAML 1.0

# TODO: XML support? YAML support?
# TODO: use something other than localhost?
# TODO: HTTPS
# TODO: examples for ALL the things!

title: Library App
description: >
  An app for a school (and possibly general) library. Currently in the early
  development/design stages, will change a lot.
version: v0
baseUri: /{version}
mediaType: application/json
uses:
  types: types.raml
securitySchemes:
  oauth2: !include security.raml
securedBy:
  - oauth2
annotationTypes:
  permissions: !include permissions.raml
resourceTypes:
  collection:
    usage: Apply on a collection for standard `GET` and `POST` methods.
    get:
      description: >
        Get a list of all <<resourcePathName | !pluralize>>. Can be sorted and
        supports pagination.
      (permissions): <<resourcePathName | !lowercase | !singularize>>.read
      queryParameters:
        # TODO extract sortable (?), pageable trait(s)?
        page:
          description: The page to retrieve, zero-indexed.
          type: integer
          default: 0
        per_page:
          description: >
            How many <<resourcePathName | !pluralize>> to include in the list in
            the response.
          type: integer
          minimum: 1
          maximum: 200
          default: 30
        sort_by:
          description: >
            What to sort the returned <<resourcePathName | !pluralize>> list by.
          enum: # TODO any more sort_by values?
            - created
            - name
          default: created
        direction:
          order: >
            The order in which to sort the <<resoucePathName | !pluralize>> --
            either ascending or descending.
          enum:
            - asc
            - desc
          default: asc
      responses:
        200:
          body:
            properties:
              items: types.<<resourcePathName|!uppercamelcase|!singularize>>[]
              hasMore: boolean
              maxItems: integer
              remainingItems: integer
        422: # Unprocessable Entity - semantic error
          properties:
            msg: string
    post:
      description: Create a new <<resourcePathName | !singularize>>.
      (permissions): <<resourcePathName | !lowercase | !singularize>>.write
      body:
        type: types.<<resourcePathName | !uppercamelcase | !singularize>>
      responses:
        201:
          headers:
            Location: string
        400:
          properties:
            msg: string