#%RAML 1.0 Library

types:
  Permission:
    enum:
      - item.read
      - item.write
      - patron.read
      - patron.write
      - checkout.read
      - checkout.write
      - admin.read
      - admin.write
      - signIn
      - signOut