#%RAML 1.0 AnnotationType

description: >
  Used to show what permissions an admin must have to use the resource or
  method. If applied on a resource, the permissions are for all methods on
  the resource; if applied to a method directly, the permissions are for
  that specific method only.
uses:
  perm-type: permission-type.raml
type: nil | perm-type.Permission | perm-type.Permission[]
allowedTargets:
  - Resource
  - Method