#%RAML 1.0 AnnotationType

description: >
  Used to show what permissions an admin must have to use the resource or
  method. If applied on a resource, the permissions are for all methods on
  the resource; if applied to a method directly, the permissions are for
  that specific method only.
  
  The permission types are:
  - item.read
  - item.write
  - patron.read
  - patron.write
  - checkout.read
  - checkout.write
  - admin.read
  - admin.write
  - signIn
  - signOut
  
  This isn't enforced because of a bug in raml2html/raml2obj/raml-js-parser
  where <<resourceTypeParameters>> aren't substituted before validation, so it
  fails when a <<parameter>> is used for the permission type.
type: nil | string | string[]
allowedTargets:
  - Resource
  - Method